
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_demo'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_demo'

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  dbt_demo:
    +post-hook: 
      - "GRANT SELECT ON {{ this }} TO ROLE REPORTER_AIRBNB"
    # Config indicated by + and applies to all files under models/example/
    staging:
      +database: stg
      +schema: airbnb
      +materialized: table
    integration:
      +database: int
      +schema: airbnb
      +materialized: table
    dwh:
      +database: dwh
      +schema: airbnb
      +materialized: table


seeds:
  dbt_demo:
    +database: int
    +schema: airbnb


